# Generated by Django 4.2 on 2025-04-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=30, null=True),
        ),
    ]
