# Generated by Django 4.2 on 2025-04-04 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_medico_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='CRM deve estar no formato XX/XXXXX, exemplo: 22/12345.', regex='^\\d{2}/\\d{5}$')]),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Insira um e-mail válido.')]),
        ),
    ]
